# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0002_auto_20160309_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
