# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
