# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0005_auto_20160310_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
