# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0006_auto_20160310_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStopCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=10)),
                ('bus_stop_name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
