# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0007_busstopcoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstopcoordinates',
            name='marker',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
