# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0008_busstopcoordinates_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=150)),
                ('Path', models.TextField(max_length=400000)),
            ],
        ),
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vertex1', models.CharField(max_length=150)),
                ('Vertex2', models.CharField(max_length=150)),
                ('Weight', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vertices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
