# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0009_bus_edges_vertices'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
